### ISSUE TITLE
It is broken

### ISSUE THREAD

**Issue by marcelaraujo** [leifriksheim/socialsurfing#1]
![screen shot 2017-09-16 at 11 42 53 am](https://user-images.githubusercontent.com/421794/30513117-3e055942-9ad4-11e7-86fb-0ca6e632595a.png)

**Comment by leifriksheim** [comment]
Think it's fixed now. Let me know if it works!

Edit: Never mind, I'll look more into it.

**Comment by leifriksheim** [comment]
It should work now :)

**Comment by marcelaraujo** [comment]
Nope, it didn't. It doesn't show anything on development console and there's only one request to another domain.

<img width="1726" alt="screen shot 2017-09-17 at 7 03 52 pm" src="https://user-images.githubusercontent.com/421794/30525342-0c8fed8e-9bdb-11e7-87d0-a329cbf2c84c.png">

**Comment by marcelaraujo** [comment]
On Safari I got this error.
<img width="1261" alt="screen shot 2017-09-17 at 7 07 10 pm" src="https://user-images.githubusercontent.com/421794/30525357-7d7e5d64-9bdb-11e7-8e29-c3fa81eeffb6.png">
